# base image
FROM node:12.2.0-alpine

# set working directory
WORKDIR /app/front-redis-poc

# add `/app/front-redis-poc/node_modules/.bin` to $PATH
ENV PATH /app/front-redis-poc/node_modules/.bin:$PATH

# install and cache app dependencies
COPY front-redis-poc/ /app/front-redis-poc/
RUN npm install
RUN npm install @vue/cli@3.7.0 -g

# start app
CMD ["npm", "run", "serve"]