version: "3.2"
services:
  front-redis-poc:
    build:
      context: ./
      dockerfile: Dockerfile-front
    container_name: front-redis-poc
    volumes:
      - ./:/usr/src/app/front-redis-poc
      - ./:/usr/src/app/front-redis-poc/node_modules'
    ports:
      - '8081:8080'
    depends_on:
      - api-redis-poc

  api-redis-poc:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: "api-redis-poc"
#    command: gunicorn django_redis_poc.wsgi_django:application --bind 0.0.0.0:8000
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/usr/src/app/
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - db-redis-poc
      - redis-poc

  redis-poc:
    container_name: "redis-poc"
    image: "redis:alpine"
    command: redis-server
    ports:
     - "6379:6379"
    volumes:
     - $PWD/redis-data:/var/lib/redis
     - $PWD/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
     - REDIS_REPLICATION_MODE=master

  nginx-poc:
    build:
      context: ./nginx
      dockerfile: Dockerfile-nginx
    ports:
      - 1337:80
    depends_on:
      - api-redis-poc

  db-redis-poc:
    container_name: "db-redis-poc"
    image: postgres:12.0-alpine
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    env_file:
      - ./.env.db


volumes:
  postgres-data:
  redis-data: