version: "3.2"
services:
  web-redis-poc:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: "web-redis-poc"
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/usr/src/app/
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - db-redis-poc
      - redis-poc

  redis-poc:
    container_name: "redis-poc"
    image: "redis:alpine"
    command: redis-server
    ports:
     - "6379:6379"

    volumes:
     - $PWD/redis-data:/var/lib/redis
     - $PWD/redis.conf:/usr/local/etc/redis/redis.conf

    environment:
     - REDIS_REPLICATION_MODE=master

  db-redis-poc:
    container_name: "db-redis-poc"
    image: postgres:12.0-alpine
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=redis_poc_user
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=redis_poc_dev

volumes:
  postgres-data:
  redis-data: